### ISSUE TITLE
[Progress Bar original] Addon Startup failed on anki 23.10

### ISSUE THREAD

**Issue by karimdjemai** [BluMist/reviewer_progress_bar#5]
Progress Bar original won't start on Anki 23.10 with the following debug information:
Anki 23.10.1 (fac9e0e) Python 3.11.6 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.6.2-arch1-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-12-10 12:18:27

When loading Progress Bar original:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 245, in loadAddons
    __import__(addon.dir_name)
  File "/home/marimini/.local/share/Anki2/addons21/1685464019/__init__.py", line 9, in <module>
    from . import reviewer_progress_bar
  File "/home/marimini/.local/share/Anki2/addons21/1685464019/reviewer_progress_bar.py", line 94, in <module>
    orientationHV = Qt.Horizontal  # Show bar horizontally (side to side). Use with top/bottom dockArea.
                    ^^^^^^^^^^^^^
AttributeError: type object 'Qt' has no attribute 'Horizontal'

## Prerequisite checklist
- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## How can we reproduce the problem?
Install the plugin via ankiweb code on the newest anki 23.10

**Comment by IntelCoreI6** [comment]
got the same issue here
