### ISSUE TITLE
Progress Bar (original): I got an error message

### ISSUE THREAD

**Issue by SpaceDuck13** [BluMist/reviewer_progress_bar#7]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19041

When loading Progress Bar original:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1685464019\__init__.py", line 9, in <module>
    from . import reviewer_progress_bar
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1685464019\reviewer_progress_bar.py", line 94, in <module>
    orientationHV = Qt.Horizontal  # Show bar horizontally (side to side). Use with top/bottom dockArea.
AttributeError: type object 'Qt' has no attribute 'Horizontal'

![image](https://github.com/BluMist/reviewer_progress_bar/assets/145936965/77911224-8296-4242-a2db-2b171205143d)

**Comment by IntelCoreI6** [comment]
hope this gets fixed soon

**Comment by jvasquezma33** [comment]
hope this gets fixed soon please, please
